# Generated by Django 6.1.1 on 2026-09-17 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_match_id', models.UUIDField(unique=True)),
                ('source_room_id', models.UUIDField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('tournament', 'Tournament'), ('quick', 'Quick'), ('private', 'Private')], max_length=20)),
                ('tournament_id', models.BigIntegerField(blank=True, null=True)),
                ('fixture_id', models.BigIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('engine', models.CharField(blank=True, default='', max_length=50)),
                ('engine_version', models.CharField(blank=True, default='', max_length=100)),
                ('input_payload', models.JSONField()),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_game_id', models.CharField(max_length=100)),
                ('game_number', models.PositiveIntegerField()),
                ('winner', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('win_type', models.CharField(max_length=30)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('input_events', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='analysis.matchanalysis')),
            ],
            options={
                'ordering': ('game_number',),
            },
        ),
        migrations.CreateModel(
            name='PlayerGameAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('game_rating', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('luck', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('equity_lost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('checker_pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('checker_errors', models.PositiveIntegerField(blank=True, null=True)),
                ('checker_blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('cube_pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cube_errors', models.PositiveIntegerField(blank=True, null=True)),
                ('cube_blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.PositiveIntegerField(blank=True, null=True)),
                ('blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='analysis.gameanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField()),
                ('turn_number', models.PositiveIntegerField(blank=True, null=True)),
                ('source_event_sequence', models.IntegerField(blank=True, null=True)),
                ('decision_type', models.CharField(choices=[('checker_move', 'Checker move'), ('double', 'Double'), ('no_double', 'No double'), ('take', 'Take'), ('pass', 'Pass'), ('redouble', 'Redouble'), ('too_good', 'Too good')], max_length=30)),
                ('dice', models.JSONField(blank=True, default=list)),
                ('played_action', models.JSONField(blank=True, null=True)),
                ('best_action', models.JSONField(blank=True, null=True)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('played_equity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('best_equity', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('equity_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('classification', models.CharField(choices=[('unclassified', 'Unclassified'), ('correct', 'Correct'), ('inaccuracy', 'Inaccuracy'), ('error', 'Error'), ('blunder', 'Blunder')], default='unclassified', max_length=20)),
                ('position_snapshot', models.JSONField(blank=True, default=dict)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_game_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='analysis.playergameanalysis')),
            ],
            options={
                'ordering': ('sequence_number',),
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_player_id', models.BigIntegerField(db_index=True)),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black')], max_length=5)),
                ('pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('game_rating', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('luck', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('equity_lost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('checker_pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('checker_equity_lost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('checker_errors', models.PositiveIntegerField(blank=True, null=True)),
                ('checker_blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('cube_pr', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cube_equity_lost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('cube_errors', models.PositiveIntegerField(blank=True, null=True)),
                ('cube_blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('errors', models.PositiveIntegerField(blank=True, null=True)),
                ('blunders', models.PositiveIntegerField(blank=True, null=True)),
                ('decisions_analyzed', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='analysis.matchanalysis')),
            ],
        ),
        migrations.AddField(
            model_name='playergameanalysis',
            name='match_player_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='analysis.playermatchanalysis'),
        ),
        migrations.AddConstraint(
            model_name='gameanalysis',
            constraint=models.UniqueConstraint(fields=('match_analysis', 'game_number'), name='unique_analysis_game_number'),
        ),
        migrations.AddConstraint(
            model_name='gameanalysis',
            constraint=models.UniqueConstraint(fields=('match_analysis', 'source_game_id'), name='unique_analysis_source_game'),
        ),
        migrations.AddConstraint(
            model_name='decisionanalysis',
            constraint=models.UniqueConstraint(fields=('player_game_analysis', 'sequence_number'), name='unique_player_decision_sequence'),
        ),
        migrations.AddConstraint(
            model_name='playermatchanalysis',
            constraint=models.UniqueConstraint(fields=('match_analysis', 'color'), name='unique_match_analysis_color'),
        ),
        migrations.AddConstraint(
            model_name='playermatchanalysis',
            constraint=models.UniqueConstraint(fields=('match_analysis', 'source_player_id'), name='unique_match_analysis_player'),
        ),
        migrations.AddConstraint(
            model_name='playergameanalysis',
            constraint=models.UniqueConstraint(fields=('game_analysis', 'match_player_analysis'), name='unique_game_player_analysis'),
        ),
    ]
