# Generated by Django 6.1.1 on 2026-09-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanalysis',
            name='black_score_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='black_score_before',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='is_crawford',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='white_score_after',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameanalysis',
            name='white_score_before',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
