# Generated by Django 6.1.1 on 2026-09-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_gameanalysis_black_score_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RollLuckAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_sequence', models.PositiveIntegerField()),
                ('dice', models.JSONField(default=list)),
                ('is_opening_roll', models.BooleanField(default=False)),
                ('luck', models.DecimalField(decimal_places=8, max_digits=12)),
                ('actual_equity', models.DecimalField(decimal_places=8, max_digits=12)),
                ('average_equity', models.DecimalField(decimal_places=8, max_digits=12)),
                ('ply', models.PositiveSmallIntegerField()),
                ('level_label', models.CharField(blank=True, default='', max_length=32)),
                ('position_snapshot', models.JSONField(default=dict)),
                ('raw_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_game_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luck_rolls', to='analysis.playergameanalysis')),
            ],
            options={
                'ordering': ['source_event_sequence'],
                'indexes': [models.Index(fields=['player_game_analysis', 'source_event_sequence'], name='luck_player_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('player_game_analysis', 'source_event_sequence'), name='unique_player_game_luck_roll')],
            },
        ),
    ]
