# Generated by Django 6.1.1 on 2026-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_matchanalysis_eval_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchanalysis',
            name='source_type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('quick', 'Quick'), ('private', 'Private'), ('ai', 'AI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='playermatchanalysis',
            name='source_player_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
